### ISSUE TITLE
hash and bytes fail to validate on empty files

### ISSUE THREAD

**Issue by zaneselvans** [ezwelty/goodtables-pandas-py#2]
I've come across an issue where the hash and bytes values fail to validate when a tabular data resource is empty (i.e it has a header row, but no data rows). For me this comes up in validating the EPA CEMS for Idaho in 1995 and 1996 (before any facilities in the state were reporting data).  The EPA CEMS data is also compressed, and part of a group of resources that end up being turned into a single database table, but other state/year combinations that share all those attributes except they aren't zero length seem to validate just fine.

**Comment by ezwelty** [comment]
@zaneselvans What do you mean by "the hash and bytes values fail to validate" ? Could you share any error output, or a minimal working example? My guess from what you describe is that this is an issue with `goodtables`, which is currently used to make basic checks (and abort further validation if errors are found) before `pandas` kicks in.

**Comment by zaneselvans** [comment]
In the datapackage standard each resource can have a `hash` attribute and a `bytes` attribute, indicating the expected `md5` or `sha256` or whatever hash value, an the file size in bytes, and for compressed resources, they're supposed to refer to the hash and filesize [of the compressed file on disk](https://specs.frictionlessdata.io/patterns/#compression-of-resources), but for some reason when the resource itself is empty, it seems to be calculating the bytes and hash of the uncompressed file (which is just a single header row) -- anyway it seems like this behavior is manifesting identically in both `goodtables` and `goodtables-pandas` so I think you're right that it's a `goodtables` issue.  I'll go make a note of it over there.
