### ISSUE TITLE
Issues with pandas 1.3.x and frictionless 3.48?

### ISSUE THREAD

**Issue by zaneselvans** [ezwelty/goodtables-pandas-py#4]
Sorry this is just a placeholder for the moment. I've come across what seems like some strange behavior in goodtables_pandas while trying to get PUDL working with pandas v1.3.x, notes in the comments on [this issue in the PUDL repo](https://github.com/catalyst-cooperative/pudl/issues/1070). Namely:
* A `KeyError` during validation that seems to have something to do with finding NA values where they aren't expected.
* A default memory limit via frictionless v3.48 of 1000MB
* A small (but unclear?) default row-validation limit via frictionless v3.48
* Weirdly small, and strangely round (in powers of two) values for `bytes` in the resource validation report output. Lots of exactly 8k, 16k, 32k, 64k values, for tables that are tens of thousands of lines long in some cases -- the CSVs are much bigger. But maybe I'm misinterpreting what `bytes` is supposed to mean in the validation report.

Pandas v1.3 changes some things about how nullable ExtensionArray data types are propagated / preserved through various operations, and I'm wondering if that's the root of the error?

**Comment by ezwelty** [comment]
@zaneselvans `goodtables_pandas.validate()` only calls `frictionless.validate_package()` to check that the file is readable and that the header is properly formatted, so any memory limits in `frictionless` should not apply (passing `limit_memory=8GB` should not matter, and this is probably why `bytes` are small and wrong – I never got around to updating the value to the whole file...). In fact, to limit what `frictionless` does (for speed), it passes several options to `frictionless.validate_package()`, including `query=frictionless.Query(limit_rows=1)`. So it doesn't make sense to set `query=frictionless.Query(limit_rows=100000)`.

As for the KeyError, I'm not sure. Do things work as expected if you set `frictionless` back to v3.34? Or `pandas` to v1.2? I will probably need your data package, or a MWE, to dig into this further.

**Comment by zaneselvans** [comment]
On pandas 1.3.2 with frictionless 3.48, where `datapkg_json` is a Path to the `datapackage.json` file, this produces the out of memory error in the top level `report['errors']`:
```py
report = goodtables.validate(
    str(datapkg_json),
    query={
        "limitRows": 100_000_000,
    }
)
```

This produces the `KeyError` from within `goodtables_pandas`:
```py
report = goodtables.validate(
    str(datapkg_json),
    limit_memory="8GB",
    query={
        "limitRows": 100_000,
    }
)
```

And this produces no errors. And you're saying this does check all the rows of data... so I guess this is the preferred usage 😄  I think I just got tripped up by the difference between what the report indicated was being done, and what it sounds like is actually happening under the hood.
```py
report = goodtables.validate(str(datapkg_json))
```

I can send you a tarball of the datapackage (81MB), but maybe this is all expected behavior? Or would you not expect passing in the memory and row limits to affect behavior?

**Comment by ezwelty** [comment]
With both frictionless v3.34 and v3.48, `report.tables[*].stats.rows` gives the total number of rows in the table. Is this not the behavior you saw?

`bytes` and `hash` however are not correct, as they are only based on the first row. I am not very motivated to compute the right values for these (it adds overhead and isn't used for validation, since they are based on the provided file), so maybe I should just drop them from the report. I should probably also just drop `**options` from `goodtables_pandas.validate()`, since passing custom arguments to `frictionless.validate()` is likely to break things.

**Comment by ezwelty** [comment]
@zaneselvans Is there something here you still need addressed?

**Comment by zaneselvans** [comment]
Nope!
