### ISSUE TITLE
Revisiting pandas-based validation of tabular data

### ISSUE THREAD

**Issue by ezwelty** [ezwelty/goodtables-pandas-py#5]
For my new job, I need a Python (and ideally, `pandas`) based tabular data validation (and transformation) pipeline that is more flexible than what I know to already exist.

- [`goodtables-pandas`](https://github.com/ezwelty/goodtables-pandas-py)
  - Does not support custom checks.
  - Written in a hurry and desperately needs a rewrite.
- [`frictionless`](https://github.com/frictionlessdata/frictionless-py)
  - Slow for larger datasets.
  - Does not support cross-table custom checks (https://framework.frictionlessdata.io/docs/references/api-reference#check)
  - Does not support transformations (other than type coercion).
  - Checks that would be trivial to write with `pandas` can be complex to write for a data stream.
- [`pandera`](https://github.com/pandera-dev/pandera)
  - Does not support cross-table custom checks.
  - Does not support transformations (other than type coercion).
- [`great-expectations`](https://github.com/great-expectations/great_expectations)
  - Does not support cross-table custom checks (https://legacy.docs.greatexpectations.io/en/latest/autoapi/great_expectations/dataset/pandas_dataset).
  - Does not support transformations (?).

So I am writing down my thoughts here for feedback.

## Goals

The goal is to develop a flexible Python API for validating tabular data stored in memory as `pandas` `Series` or `DataFrames`.

At the minimum, one should be able to:

- Define a schema to validate a column, table, or group of tables.
- Write and read schemas to and from text-based metadata (e.g. YAML).
- Check constraints on a column (e.g. not null, integer, greater than 0), optionally in the context of the containing table (e.g. equal to column `y`) or other tables (e.g. simple foreign key: present in column `xb` of table `b`).
- Check constraints on a table (e.g. composite unique key: columns `x` and `y` are unique), optionally in the context of other tables (e.g. composite foreign key: columns `x` and `y` are present in columns `xb` and `yb` of table `b`).
- Check constraints on a group of tables (e.g. table `b` is required if table `a` is present).
- Manually control check execution.
- Optionally transform the content of the column, table, or group of tables for use in subsequent checks (e.g. parse strings as integers before checking whether greater than 0).
- Tag checks (e.g. as either errors or warnings).
- Generate a detailed validation report with check results and (optionally) check transformations.
 
Ideally, one should also be able to conditionally skip checks. This could be accomplished in a number of ways, and I am not sure on the best approach.

- Manually (flexible, easiest to implement, tricky to use).
  - Drop columns or tables in a check to signal they should not be checked further – either by returning `None` (to clear the column or entire table) or by dropping columns from a table or tables/columns from a group of tables.
  - In subsequent checks which depend on these dropped elements as context, check for them explicitly and raise a special error (caught by the check executor) if they are missing.
- Based on explicit dependencies (flexible, hardest to implement, verbose).
  - Explicitly define the scope of each check for which it is ambiguous: columns (if not the table) for table checks, tables and/or table-columns (if not all tables) for tables checks.
  - Explicitly define required dependencies of each check that has them (e.g. for a foreign key, the columns of the foreign table).
  - Within each scope, register the checks in order of execution, but let the system figure out the order of execution.
  - An error from a check skips all further checks in the scope and all other checks that dependent on it.
- Based on a reasonable default (not flexible, easy to use).
  - Order checks based on knowledge of each built-in check.
  - Unclear how to extend such a system to custom checks unless it uses explicit dependencies internally.

### Arguments

A check function must accept – as the first and required argument – the tabular data to be checked: either a column (`pd.Series`), a table (`pd.DataFrame`), or a group of tables (`Dict[Hashable, pd.DataFrame]`). It may also accept – as additional required or optional arguments – the larger tabular context: a table and/or a group of tables. For example, a column check can have any combination of the following arguments, depending on its needs:

- `s: pd.Series`
- `s: pd.Series`, `df: pd.DataFrame`
- `s: pd.Series`, `df: pd.DataFrame`, `dfs: Dict[Hashable, pd.DataFrame]`
- `s: pd.Series`, `dfs: Dict[Hashable, pd.DataFrame]`

Note that here, since `dfs` can be included without `df`, position is not enough for the system to map the arguments to tabular context. This means that a strict naming (or type annotation) convention would instead need to be followed...

Finally, a check function may also accept any number of named keyword-only arguments (following the `*`) to control the specific behavior of the check. Here are a few real examples:

```py
from typing import Dict, Hashable, Sequence
import pandas as pd

def not_null(s: pd.Series) -> pd.Series:
  """Column values are not null."""
  return s.notnull()

def in_values(
  s: pd.Series, *,
  values: Sequence
) -> pd.Series:
  """Column values are in a set of allowed values."""
  return s.isin(values) | s.isnull()

def in_foreign_column(
  s: pd.Series, dfs: Dict[Hashable, pd.DataFrame], *,
  table: Hashable, column: Hashable
) -> pd.Series:
  """Column values exist in a foreign column."""
  foreign = dfs[table][column]
  return s.isin(foreign) | s.isnull()

def unique_rows(
  df: pd.DataFrame, *,
  columns: Sequence[Hashable] = None
) -> pd.Series:
  """Rows are unique."""
  return ~df.duplicated(subset=columns, keep=False)
```

### Return values

Check functions may return a result for the input as a whole, or for each subelement:

- `Optional[bool]`: Success (`True`), failure (`False`), or skipped (`None`) for the input (column, table, or tables).
- `Union[pd.Series, Dict[Hashable, Optional[bool]]]`: Success, failure, or skipped for each subelement (cell, row, or table). The index (or keys) must match that of the input.

They may also return a new (transformed) value for the input, in which case the check result and the new value are returned as a `tuple`.

## Check class

A check function is wrapped with some metadata together into an instance of a check class. This could include:

- `fn` (`Callable`): Check function.
- `params` (`Dict[str, Any] = {}`): Values to use for the keyword-only arguments of `fn`.
- `scope` (`Literal['column', 'table', 'tables'] = None`): Whether `fn` accepts a column, table, or tables as first argument. If `None`, attempts to guess from the function signature.
- `transform` (`bool = None`): Whether `fn` also returns a new value for its first argument. If `None`, attempts to guess from the function signature.
- `message` (`str`): Message template for check failure, as a template string (with f-string syntax support) evaluated on `params`. 
- `severity` (`Literal['error', 'warning'] = 'error'`): Whether to tag check failures as errors or warnings.

The process of constructing a check can be simplified, for example, with class methods or a check function decorator that registers a new class method:

```py
from typing import Callable, Literal, Sequence
import pandas as pd

class Check:

  def __init__(
    self,
    fn: Callable,
    params: dict = None,
    scope: Literal['column', 'table', 'tables'] = None,
    transform: bool = None,
    message: str = None,
    severity = 'error'
  ) -> None:
    pass

  @classmethod
  def in_values(
    cls, values: Sequence, message = 'Value not in {values}', **kwargs: Any
  ) -> 'Check':
    return cls(
      fn=in_values,
      params={'values': values},
      scope='column',
      transform=False,
      message=message
    )

@check(message='Value not in {values}')
def in_values(s: pd.Series, *, values: Sequence) -> pd.Series:
  """Column values are in a set of allowed values."""
  return s.isin(values) | s.isnull()
```

## Schema

In this framework, a tabular data schema is represented as an ordered sequence of checks. Each check is assigned explicitly, as needed, with the name of the subelement to check: a table schema needs the name of the column to check, and a tables schema needs the name of the table/column to check. The API may provide more compact representations to simplify the construction of a schema, but internally, this is the most flexible.

```py
from typing import Hashable, Optional, Tuple

class Task:

  def __init__(
    self, check: Check, column: Hashable = None, table: Hashable = None
  ) -> None:
    self.check = check
    self.column = column
    self.table = table

class Schema:
  
  def __init__(
    self,
    tasks = Sequence[Task],
    scope: Literal['column', 'table', 'tables'] = None
  ) -> None:
    self.tasks = tasks
    self.scope = scope

  def validate(value: Any) -> Tuple[Report, Any]:
    """Validate and transform the input, returning a report and the new value."""
    pass

  @classmethod
  def from_yaml(cls, path: str) -> 'Schema':
    """Load schema from file."""
    pass

  def to_yaml(self, path: str = None) -> Optional[str]:
    """Write schema to file."""
    pass
```

### Schema conversion

Although conversion away from this schema format would not always be possible (since it is intended to be more flexible and expressive than what currently exists), it should be able to represent other schemas. As a first priority, I would want to support conversion from a Frictionless Tabular Data Package specification.

## Report

Different situations will require different reporting formats. More important is to ensure that all the pertinent information is provided, while also being mindful of memory usage.

The user, by definition, already has access to the input (tabular data to validate) and the output (transformed tabular data). The report can provide the metadata and check results at each intermediate step:

- `check` (`Check`): Check instance.
- `table` (`Hashable = None`): Name of table that was checked.
- `column` (`Hashable = None`): Name of column that was checked.
- `success` (`Union[bool, pd.Series, Dict[Hashable, Optional[bool]]] = None`): Check result. Unless this is a scalar, this also contains the names of the rows or tables that were checked. To reduce memory usage, this could be reduced to only failure cases, or just the first `n` failure cases (e.g. `Check.n_failure_cases` in [`pandera`](https://pandera.readthedocs.io/en/stable/reference/generated/pandera.checks.Check.html#pandera.checks.Check)).

A simple formatting of the results could look like this:

| table     | column         | check                                                                                                               | row   | value   | message                                                                                              |
|-----------|----------------|---------------------------------------------------------------------------------------------------------------------|-------|---------|------------------------------------------------------------------------------------------------------|
| main      | integer_pk     | Check.not_null()                                                                                                    | 3     | `<NA>`    | Required value is missing                                                                            |
| main      | integer_minmax | Check.parse_as_type(type=integer)                                                                                   | 1     | 1.2     | Value could not be parsed to type integer                                                            |
| main      | integer_minmax | Check.less_than_or_equal_to(max=10)                                                                                 | 2     | 11      | Value > 10                                                                                           |
| main      | number_minmax  | Check.parse_as_type(type=number)                                                                                    | 1     | 'a'       | Value could not be parsed to type number                                                             |
| main      | number_minmax  | Check.less_than_or_equal_to(max=10)                                                                                 | 2     | 11.0    | Value > 10                                                                                           |
| main      | boolean        | Check.parse_as_type(type=boolean)                                                                                   | 2     | 'a'       | Value could not be parsed to type boolean                                                            |
| main      | string_minmax  | Check.length_greater_than_or_equal_to(min=2)                                                                        | 1     | 'a'       | Length < 2                                                                                           |
| main      | string_minmax  | Check.length_less_than_or_equal_to(max=3)                                                                           | 2     | 'abcd'    | Length > 3                                                                                           |
| main      | string_enum    | Check.in_list(values=['a', 'b'])                                                                                    | 2     | 'f'       | Value not in ['a', 'b']                                                                              |
| main      | string_regex   | Check.matches_regex(regex=[ab])                                                                                     | 2     | 'f'       | Value does not match regular expression [ab]                                                         |
| secondary | integer_pk     | Check.in_foreign_column(table=main, column=integer_pk)                                                              | 3     | 4       | Not found in main.integer_pk                                                                         |
| secondary | string_pk      | Check.not_null()                                                                                                    | 3     | <NA>    | Required value is missing                                                                            |
| secondary |                | Check.unique_rows(columns=['integer_pk', 'string_pk'])                                                              |       |         | Duplicate combination of columns ['integer_pk', 'string_pk']                                         |
| secondary |                | Check.matches_foreign_columns(table=main, join={'integer_pk': 'integer_pk'}, columns={'boolean_lookup': 'boolean'}) |       |         | Columns ['boolean_lookup'] do not match main.['boolean'] when joined on {'integer_pk': 'integer_pk'} |

**Comment by zaneselvans** [comment]
What do you mean when you say it needs to support "transformation?" Just things like type coercion so that the data can be validated against subsequent checks?

This has to be such a common set of problems that I still have a hard time believing the tools just don't exist. Are you still thinking about potentially trying to extend one of the existing tools? Or definitely building something from scratch?

One context I imagine this kind of stuff must come up in a lot is when folks are using columnar databases / data warehouses like BigQuery, since they seem to have less stringent inter-table schemas / constraint enforcement than row-oriented DBs like Postgres. So far as I can tell the most popular tool in that context is `dbt`. Have you looked at [dbt and its data testing facilities](https://www.getdbt.com/product/data-testing/)? It's much more database / data warehouse centered, but I think it's trying to solve a similar set of issues. In addition to columnar cloud DBs it can also use Postgres locally.

**Comment by ezwelty** [comment]
@zaneselvans For now, I'm continuing down my own path. I would rather adopt something already in production, but I'm still looking for something that meets my needs.

In the SQL-verse, `dbt` comes close (and will be worth a deeper look), but it assumes stable sources (https://docs.getdbt.com/docs/building-a-dbt-project/using-sources) as a starting point for data transformations (and testing along the way). So for example, testing for the existence of a source table (or column) is a very edge case: https://discourse.getdbt.com/t/writing-packages-when-a-source-table-may-or-may-not-exist/1487.

In contrast, I need to transform many, variable sources (that theoretically are identically-structured, but aren't) to a common pre-defined schema, fixing some issues automatically and reporting others that a human needs to fix. So by "transformation", I mean parsing values from raw strings (and reporting those that failed, while still passing them downstream as `null`) but also things like trimming whitespace in strings (before parsing), rounding floats to integers (after parsing), filling missing tables and columns with defaults, etc.

**Comment by zaneselvans** [comment]
I've been struggling to understand how all these big ETL/ELT tools deal with the messy first steps of data processing where you don't really have real "tables" yet, and have to muck around with the contents and structures in bespoke ways. Like do people really do that in SQL and I just have no idea what that kind of SQL would look like? Or is all the horrible preprocessing done in Python/R and there's just no good widespread organizational structure / tooling for doing that in a controlled way?

**Comment by ezwelty** [comment]
@zaneselvans I made a thing that implements much of what I discussed above:
https://github.com/ezwelty/validator

The syntax / API could be further improved (see the issues on that repo), but nevertheless I've been using it pretty successfully at my work to define and organize the many tabular data validation/transformation pipelines we need to manage. The flexibility of the framework can make the resulting schemas somewhat inscrutable at times, but it also allows me to accomplish a lot of things with just one tool.
